repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.3.7
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]
  - id: ruff-format

# should be replaced in the future ref https://github.com/astral-sh/ruff/issues/458
- repo: https://github.com/jsh9/pydoclint
  rev: 0.4.1
  hooks:
  - id: pydoclint

# should be replaced in the future ref https://github.com/astral-sh/ruff/issues/3792
- repo: https://github.com/asottile/blacken-docs
  rev: 1.16.0
  hooks:
  - id: blacken-docs
    additional_dependencies: ['black==24.2.0']

# - repo: local
#   hooks:
#   - id: mypy
#     name: Run mypy
#     entry: python -m mypy --install-types --non-interactive --cache-dir=.mypy_cache/ app/
#     language: system
#     types: [python]
#     pass_filenames: false

- repo: https://github.com/pappasam/toml-sort
  rev: v0.23.1
  hooks:
  - id: toml-sort-fix
    args: ['--trailing-comma-inline-array']

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: mixed-line-ending
    args: ['--fix=lf']
  - id: trailing-whitespace
  - id: end-of-file-fixer
    exclude: \.(svg)$
  - id: check-merge-conflict
  - id: check-json
  - id: check-toml
  - id: check-xml
  - id: check-yaml
