{
 "title": "parkinson-disease-prediction-dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total Request",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "request_count_total", "legendFormat": "Total Request" }
   ]
  },
  {
   "title": "CPU Usage (s)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 0 },
   "targets": [
    { "expr": "process_cpu_seconds_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(request_latency_seconds_sum[1m])) / sum(rate(request_count_total[1m]))",
     "legendFormat": "request latency avg"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "mem" }
   ]
  },
  {
   "title": "Total Yes/No Prediction Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "parkinson_disease_predictions_no_total",
     "legendFormat": "total NO"
    }
   ]
  }
 ]
}