name: CI-Tests
on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install linter dependencies
        run: pip install -r requirements.ci.txt

      - name: Run unit tests
        run:  pytest tests

      - name: Lint
        run:  pre-commit run --all-files

      - name: Integration Test
        run: LOCAL_IMAGE_NAME=parkinson-disease-prediction:latest cd integration_test && ./run.sh

  tf-plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-central-1"

      - uses: hashicorp/setup-terraform@v2

      - name: TF plan
        id: plan
        working-directory: 'infrastructure'
        run: |
          terraform init -backend-config="key=parkinson-disease-prediction-stg.tfstate" --reconfigure && terraform plan --var-file vars/stg.tfvars
